### ISSUE TITLE
Script to display list of Hive databases built on HDFS

### ISSUE THREAD

**Issue by kmadhugit** [josiahsams/tpcds-setup#3]
Add this script ..

madhu@n001:~/tpcds-setup$ cat showdbs.sh 
echo "use metastore_db; select DB_LOCATION_URI,NAME,OWNER_NAME from DBS;" | mysql -uhive -pxxxx

**Comment by josiahsams** [comment]
Added it via commit [42e5e40](https://github.com/josiahsams/tpcds-setup/commit/42e5e408f8d22048b5a0a3be6feffee0a4678e44)
